name = "swinix"
license = "MIT"
licenselink = "https://github.com/cleverswine/hugo-swinix/blob/master/LICENSE"
description = "Yet another theme for *nix users"
homepage = "https://github.com/cleverswine/hugo-swinix"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Kevin Noone"
  homepage = "http://knoone.info"