baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Title"
author = "The Author"
paginate = 12
theme = "hugo-swinix"
themesDir = "../.."

[params]
  # Name = "Your Name"
  # Description = "Software Engineer in USA"
  # ProfilePicture = "/profile.jpg"
  # UserName = "yourname"
  [params.contact]
    github = "https://github.com/username"
    twitter = "https://twitter.com/username/"
    linkedin = "https://www.linkedin.com/in/username/"
    flickr = "http://www.flickr.com/photos/username/"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/pages/about"